linters-settings:
  errcheck:
    exclude-functions:
      - github.com/gadget-inc/fusion/internal/timer.Loop
      - (net/http.ResponseWriter).Write
      - (k8s.io/client-go/testing.ObjectTracker).Add
      - (k8s.io/client-go/testing.ObjectTracker).Create
