version: 3

tasks:
  build:
    label: "build {{.CLI_ARGS}}"
    sources:
      - cmd/**/*.go
      - internal/**/*.go
      - pkg/**/*.go
      - .goreleaser.yaml
      - go.mod
      - go.sum
      - main.go
    generates:
      - dist/*
    cmds:
      - goreleaser build --clean --snapshot {{.CLI_ARGS}}

  docker-build:
    deps:
      - build
    sources:
      - dist/**/*
      - docker/**/*
      - scripts/docker-build.ts
    cmds:
      - deno run -A scripts/docker-build.ts

  docker-push:
    deps:
      - docker-build
    cmds:
      - deno run -A scripts/docker-push.ts

  deploy:
    deps:
      - docker-build
    cmds:
      - deno run -A scripts/deploy.ts

  example-deno-request:
    cmds:
      - deno run -A scripts/example-deno-request.ts

  example-deno-websocket:
    cmds:
      - node scripts/nodejs/example-deno-websocket.js
