version: 3

tasks:
  build:
    label: "build {{.CLI_ARGS}}"
    sources:
      - cmd/**/*.go
      - internal/**/*.go
      - pkg/**/*.go
      - .goreleaser.yaml
      - go.mod
      - go.sum
      - main.go
    generates:
      - dist/*
    cmds:
      - goreleaser build --clean --snapshot {{.CLI_ARGS}}

  docker-build:
    deps:
      - build
    sources:
      - dist/**/*
      - docker/**/*
      - scripts/docker-build.ts
    cmds:
      - deno run -A scripts/docker-build.ts

  docker-push:
    deps:
      - docker-build
    sources:
      - scripts/docker-push.ts
    cmds:
      - deno run -A scripts/docker-push.ts

  deploy:
    deps:
      - docker-build
    sources:
      - deploy/**/*
      - scripts/deploy.ts
    cmds:
      - deno run -A scripts/deploy.ts

  serve:
    cmds:
      - task: build
        vars:
          CLI_ARGS: --single-target
      - ./dist/fusion_darwin_arm64_v8.0/fusion serve --namespace=example-development --log-format=text --log-level=debug --fusion-namespace=fusion-development --fusion-ip=127.0.0.1

  example-deno-request:
    cmds:
      - deno run -A scripts/example-deno-request.ts

  example-deno-websocket:
    cmds:
      - node scripts/nodejs/example-deno-websocket.js
