apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deno
  labels:
    app.kubernetes.io/managed-by: fusion
    fusion/deployment: example-deno
    fusion/status: unassigned
  annotations:
    shipit.shopify.io/restart: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/managed-by: fusion
      fusion/deployment: example-deno
      fusion/status: unassigned
  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: fusion
        fusion/deployment: example-deno
        fusion/status: unassigned
    spec:
      volumes:
        - name: empty-dir
          emptyDir: {}
      containers:
        - name: deno
          image: fusion-example-deno:latest
          imagePullPolicy: Never
          ports:
            - name: http-port
              containerPort: 8888
          env:
            - name: DENO_V8_FLAGS
              value: "--max-old-space-size=256"
          volumeMounts:
            - name: empty-dir
              mountPath: /tmp
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          startupProbe:
            httpGet:
              path: /healthz
              port: http-port
            failureThreshold: 3
            initialDelaySeconds: 3
            periodSeconds: 1
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /healthz
              port: http-port
            failureThreshold: 3
            periodSeconds: 1
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /healthz
              port: http-port
            failureThreshold: 1
            periodSeconds: 1
            successThreshold: 1
            timeoutSeconds: 1
