// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: controller.proto

package controller

import (
	function "github.com/gadget-inc/skipper/internal/function"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetOrCreateInstanceRequest struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Function *function.Function     `protobuf:"bytes,1,opt,name=function,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetOrCreateInstanceRequest) Reset() {
	*x = GetOrCreateInstanceRequest{}
	mi := &file_controller_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrCreateInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrCreateInstanceRequest) ProtoMessage() {}

func (x *GetOrCreateInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetOrCreateInstanceRequest) GetFunction() *function.Function {
	if x != nil {
		return x.xxx_hidden_Function
	}
	return nil
}

func (x *GetOrCreateInstanceRequest) SetFunction(v *function.Function) {
	x.xxx_hidden_Function = v
}

func (x *GetOrCreateInstanceRequest) HasFunction() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Function != nil
}

func (x *GetOrCreateInstanceRequest) ClearFunction() {
	x.xxx_hidden_Function = nil
}

type GetOrCreateInstanceRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Function *function.Function
}

func (b0 GetOrCreateInstanceRequest_builder) Build() *GetOrCreateInstanceRequest {
	m0 := &GetOrCreateInstanceRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Function = b.Function
	return m0
}

type GetOrCreateInstanceResponse struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Instance *function.Instance     `protobuf:"bytes,1,opt,name=instance,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetOrCreateInstanceResponse) Reset() {
	*x = GetOrCreateInstanceResponse{}
	mi := &file_controller_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrCreateInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrCreateInstanceResponse) ProtoMessage() {}

func (x *GetOrCreateInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetOrCreateInstanceResponse) GetInstance() *function.Instance {
	if x != nil {
		return x.xxx_hidden_Instance
	}
	return nil
}

func (x *GetOrCreateInstanceResponse) SetInstance(v *function.Instance) {
	x.xxx_hidden_Instance = v
}

func (x *GetOrCreateInstanceResponse) HasInstance() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Instance != nil
}

func (x *GetOrCreateInstanceResponse) ClearInstance() {
	x.xxx_hidden_Instance = nil
}

type GetOrCreateInstanceResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Instance *function.Instance
}

func (b0 GetOrCreateInstanceResponse_builder) Build() *GetOrCreateInstanceResponse {
	m0 := &GetOrCreateInstanceResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Instance = b.Instance
	return m0
}

type SendHeartbeatsRequest struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RouterIp     string                 `protobuf:"bytes,1,opt,name=router_ip,json=routerIp,proto3"`
	xxx_hidden_Heartbeats   *[]*function.Heartbeat `protobuf:"bytes,2,rep,name=heartbeats,proto3"`
	xxx_hidden_ForwardedFor []string               `protobuf:"bytes,3,rep,name=forwarded_for,json=forwardedFor,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *SendHeartbeatsRequest) Reset() {
	*x = SendHeartbeatsRequest{}
	mi := &file_controller_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendHeartbeatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendHeartbeatsRequest) ProtoMessage() {}

func (x *SendHeartbeatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SendHeartbeatsRequest) GetRouterIp() string {
	if x != nil {
		return x.xxx_hidden_RouterIp
	}
	return ""
}

func (x *SendHeartbeatsRequest) GetHeartbeats() []*function.Heartbeat {
	if x != nil {
		if x.xxx_hidden_Heartbeats != nil {
			return *x.xxx_hidden_Heartbeats
		}
	}
	return nil
}

func (x *SendHeartbeatsRequest) GetForwardedFor() []string {
	if x != nil {
		return x.xxx_hidden_ForwardedFor
	}
	return nil
}

func (x *SendHeartbeatsRequest) SetRouterIp(v string) {
	x.xxx_hidden_RouterIp = v
}

func (x *SendHeartbeatsRequest) SetHeartbeats(v []*function.Heartbeat) {
	x.xxx_hidden_Heartbeats = &v
}

func (x *SendHeartbeatsRequest) SetForwardedFor(v []string) {
	x.xxx_hidden_ForwardedFor = v
}

type SendHeartbeatsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RouterIp     string
	Heartbeats   []*function.Heartbeat
	ForwardedFor []string
}

func (b0 SendHeartbeatsRequest_builder) Build() *SendHeartbeatsRequest {
	m0 := &SendHeartbeatsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_RouterIp = b.RouterIp
	x.xxx_hidden_Heartbeats = &b.Heartbeats
	x.xxx_hidden_ForwardedFor = b.ForwardedFor
	return m0
}

type SendHeartbeatsResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendHeartbeatsResponse) Reset() {
	*x = SendHeartbeatsResponse{}
	mi := &file_controller_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendHeartbeatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendHeartbeatsResponse) ProtoMessage() {}

func (x *SendHeartbeatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type SendHeartbeatsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 SendHeartbeatsResponse_builder) Build() *SendHeartbeatsResponse {
	m0 := &SendHeartbeatsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ScaleRequest struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Function         *function.Function     `protobuf:"bytes,1,opt,name=function,proto3"`
	xxx_hidden_DesiredInstances uint32                 `protobuf:"varint,2,opt,name=desired_instances,json=desiredInstances,proto3"`
	xxx_hidden_Reason           string                 `protobuf:"bytes,3,opt,name=reason,proto3"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *ScaleRequest) Reset() {
	*x = ScaleRequest{}
	mi := &file_controller_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScaleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScaleRequest) ProtoMessage() {}

func (x *ScaleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ScaleRequest) GetFunction() *function.Function {
	if x != nil {
		return x.xxx_hidden_Function
	}
	return nil
}

func (x *ScaleRequest) GetDesiredInstances() uint32 {
	if x != nil {
		return x.xxx_hidden_DesiredInstances
	}
	return 0
}

func (x *ScaleRequest) GetReason() string {
	if x != nil {
		return x.xxx_hidden_Reason
	}
	return ""
}

func (x *ScaleRequest) SetFunction(v *function.Function) {
	x.xxx_hidden_Function = v
}

func (x *ScaleRequest) SetDesiredInstances(v uint32) {
	x.xxx_hidden_DesiredInstances = v
}

func (x *ScaleRequest) SetReason(v string) {
	x.xxx_hidden_Reason = v
}

func (x *ScaleRequest) HasFunction() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Function != nil
}

func (x *ScaleRequest) ClearFunction() {
	x.xxx_hidden_Function = nil
}

type ScaleRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Function         *function.Function
	DesiredInstances uint32
	Reason           string
}

func (b0 ScaleRequest_builder) Build() *ScaleRequest {
	m0 := &ScaleRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Function = b.Function
	x.xxx_hidden_DesiredInstances = b.DesiredInstances
	x.xxx_hidden_Reason = b.Reason
	return m0
}

type ScaleResponse struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Instances *[]*function.Instance  `protobuf:"bytes,1,rep,name=instances,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ScaleResponse) Reset() {
	*x = ScaleResponse{}
	mi := &file_controller_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScaleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScaleResponse) ProtoMessage() {}

func (x *ScaleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ScaleResponse) GetInstances() []*function.Instance {
	if x != nil {
		if x.xxx_hidden_Instances != nil {
			return *x.xxx_hidden_Instances
		}
	}
	return nil
}

func (x *ScaleResponse) SetInstances(v []*function.Instance) {
	x.xxx_hidden_Instances = &v
}

type ScaleResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Instances []*function.Instance
}

func (b0 ScaleResponse_builder) Build() *ScaleResponse {
	m0 := &ScaleResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Instances = &b.Instances
	return m0
}

var File_controller_proto protoreflect.FileDescriptor

const file_controller_proto_rawDesc = "" +
	"\n" +
	"\x10controller.proto\x12\n" +
	"controller\x1a\x0efunction.proto\x1a\x0einstance.proto\x1a\x0fheartbeat.proto\"L\n" +
	"\x1aGetOrCreateInstanceRequest\x12.\n" +
	"\bfunction\x18\x01 \x01(\v2\x12.function.FunctionR\bfunction\"M\n" +
	"\x1bGetOrCreateInstanceResponse\x12.\n" +
	"\binstance\x18\x01 \x01(\v2\x12.function.InstanceR\binstance\"\x8e\x01\n" +
	"\x15SendHeartbeatsRequest\x12\x1b\n" +
	"\trouter_ip\x18\x01 \x01(\tR\brouterIp\x123\n" +
	"\n" +
	"heartbeats\x18\x02 \x03(\v2\x13.function.HeartbeatR\n" +
	"heartbeats\x12#\n" +
	"\rforwarded_for\x18\x03 \x03(\tR\fforwardedFor\"\x18\n" +
	"\x16SendHeartbeatsResponse\"\x83\x01\n" +
	"\fScaleRequest\x12.\n" +
	"\bfunction\x18\x01 \x01(\v2\x12.function.FunctionR\bfunction\x12+\n" +
	"\x11desired_instances\x18\x02 \x01(\rR\x10desiredInstances\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"A\n" +
	"\rScaleResponse\x120\n" +
	"\tinstances\x18\x01 \x03(\v2\x12.function.InstanceR\tinstances2\x91\x02\n" +
	"\n" +
	"Controller\x12h\n" +
	"\x13GetOrCreateInstance\x12&.controller.GetOrCreateInstanceRequest\x1a'.controller.GetOrCreateInstanceResponse\"\x00\x12Y\n" +
	"\x0eSendHeartbeats\x12!.controller.SendHeartbeatsRequest\x1a\".controller.SendHeartbeatsResponse\"\x00\x12>\n" +
	"\x05Scale\x12\x18.controller.ScaleRequest\x1a\x19.controller.ScaleResponse\"\x00B3Z1github.com/gadget-inc/skipper/internal/controllerb\x06proto3"

var file_controller_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_controller_proto_goTypes = []any{
	(*GetOrCreateInstanceRequest)(nil),  // 0: controller.GetOrCreateInstanceRequest
	(*GetOrCreateInstanceResponse)(nil), // 1: controller.GetOrCreateInstanceResponse
	(*SendHeartbeatsRequest)(nil),       // 2: controller.SendHeartbeatsRequest
	(*SendHeartbeatsResponse)(nil),      // 3: controller.SendHeartbeatsResponse
	(*ScaleRequest)(nil),                // 4: controller.ScaleRequest
	(*ScaleResponse)(nil),               // 5: controller.ScaleResponse
	(*function.Function)(nil),           // 6: function.Function
	(*function.Instance)(nil),           // 7: function.Instance
	(*function.Heartbeat)(nil),          // 8: function.Heartbeat
}
var file_controller_proto_depIdxs = []int32{
	6, // 0: controller.GetOrCreateInstanceRequest.function:type_name -> function.Function
	7, // 1: controller.GetOrCreateInstanceResponse.instance:type_name -> function.Instance
	8, // 2: controller.SendHeartbeatsRequest.heartbeats:type_name -> function.Heartbeat
	6, // 3: controller.ScaleRequest.function:type_name -> function.Function
	7, // 4: controller.ScaleResponse.instances:type_name -> function.Instance
	0, // 5: controller.Controller.GetOrCreateInstance:input_type -> controller.GetOrCreateInstanceRequest
	2, // 6: controller.Controller.SendHeartbeats:input_type -> controller.SendHeartbeatsRequest
	4, // 7: controller.Controller.Scale:input_type -> controller.ScaleRequest
	1, // 8: controller.Controller.GetOrCreateInstance:output_type -> controller.GetOrCreateInstanceResponse
	3, // 9: controller.Controller.SendHeartbeats:output_type -> controller.SendHeartbeatsResponse
	5, // 10: controller.Controller.Scale:output_type -> controller.ScaleResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_controller_proto_init() }
func file_controller_proto_init() {
	if File_controller_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_controller_proto_rawDesc), len(file_controller_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_controller_proto_goTypes,
		DependencyIndexes: file_controller_proto_depIdxs,
		MessageInfos:      file_controller_proto_msgTypes,
	}.Build()
	File_controller_proto = out.File
	file_controller_proto_goTypes = nil
	file_controller_proto_depIdxs = nil
}
