package key

// Pre-defined keys for common attributes used throughout skipper.
// Each key provides consistent naming across logs, traces, headers, and labels.
var (
	Addr                      = stringKey("address")
	AssignedAt                = timeKey("assigned_at")
	Attempt                   = intKey("attempt")
	CPUUsageMilli             = uint32Key("cpu_usage_milli")
	Controller                = newNames("controller")
	Count                     = intKey("count")
	Deployment                = stringKey("deployment")
	DesiredInstances          = uint32Key("desired_instances")
	Duration                  = durationKey("duration")
	Error                     = errorKey("error")
	ExcludeInstanceNames      = stringSliceKey("exclude_instance_names")
	ForwardedFor              = newNames("forwarded_for")
	GetInstanceDurationMs     = durationKey("get_instance_duration_ms")
	InFlightRequests          = uint32Key("in_flight_requests")
	K8sReplicaSet             = replicaSetKey("k8s.replicaset")
	Labels                    = mapStringStringKey("labels")
	MaxInstances              = uint32Key("max_instances")
	MemoryUsageMiB            = uint32Key("memory_usage_mib")
	Metadata                  = stringKey("metadata")
	MinInstances              = uint32Key("min_instances")
	Name                      = stringKey("name")
	Namespace                 = stringKey("namespace")
	Oneshot                   = boolKey("oneshot")
	Pod                       = podKey("k8s.pod")
	PodIP                     = stringKey("pod_ip")
	Port                      = newNames("port")
	ReadyAt                   = timeKey("ready_at")
	ReadyInstances            = intKey("ready_instances")
	Reason                    = stringKey("reason")
	ReplicaSet                = stringKey("replica_set")
	Request                   = requestKey("http.request")
	Response                  = responseKey("http.response")
	ResponsibleIP             = stringKey("responsible_ip")
	RouterIP                  = stringKey("router_ip")
	TargetCPUUsageMilli       = uint32Key("target_cpu_usage_milli")
	TargetInFlightRequests    = uint32Key("target_in_flight_requests")
	TargetMemoryUsageMiB      = uint32Key("target_memory_usage_mib")
	Tenant                    = stringKey("tenant")
	Timestamp                 = timeKey("timestamp")
	Token                     = newNames("token")
	URL                       = urlKey("url")
	UnclampedDesiredInstances = uint32Key("unclamped_desired_instances")
	UnreadyInstances          = intKey("unready_instances")
)
