package key

// Pre-defined keys for common attributes used throughout skipper.
// Each key provides consistent naming across logs, traces, headers, and labels.
var (
	Addr                      = stringKey("address")
	AssignedAt                = timeKey("assigned_at")
	Attempt                   = intKey("attempt")
	CPUUsageMilli             = uint64Key("cpu_usage_milli")
	Controller                = newIdentifier("controller")
	Count                     = intKey("count")
	Deployment                = stringKey("deployment")
	DesiredInstances          = uint64Key("desired_instances")
	Duration                  = durationKey("duration")
	Error                     = errorKey("error")
	ExcludeInstanceNames      = stringSliceKey("exclude_instance_names")
	ForwardedFor              = newIdentifier("forwarded_for")
	Function                  = logValuerKey("function")
	GetInstanceDurationMs     = durationKey("get_instance_duration_ms")
	Heartbeat                 = logValuerKey("heartbeat")
	InFlightRequests          = uint64Key("in_flight_requests")
	Instance                  = logValuerKey("instance")
	K8sReplicaSet             = replicaSetKey("k8s.replicaset")
	Labels                    = mapStringStringKey("labels")
	MaxInstances              = uint64Key("max_instances")
	MemoryUsageMiB            = uint64Key("memory_usage_mib")
	Metadata                  = stringKey("metadata")
	MinInstances              = uint64Key("min_instances")
	Name                      = stringKey("name")
	Namespace                 = stringKey("namespace")
	Pod                       = podKey("k8s.pod")
	Port                      = newIdentifier("port")
	ReadyAt                   = timeKey("ready_at")
	ReadyInstances            = intKey("ready_instances")
	Reason                    = stringKey("reason")
	ReplicaSet                = stringKey("replica_set")
	Request                   = requestKey("http.request")
	Response                  = responseKey("http.response")
	ResponsibleIP             = stringKey("responsible_ip")
	RouterIP                  = stringKey("router_ip")
	Scale                     = logValuerKey("scale")
	ScaleDecision             = logValuerKey("scale_decision")
	TargetCPUUsageMilli       = uint64Key("target_cpu_usage_milli")
	TargetInFlightRequests    = uint64Key("target_in_flight_requests")
	TargetMemoryUsageMiB      = uint64Key("target_memory_usage_mib")
	Tenant                    = stringKey("tenant")
	Timestamp                 = timeKey("timestamp")
	Token                     = newIdentifier("token")
	URL                       = urlKey("url")
	UnclampedDesiredInstances = uint64Key("unclamped_desired_instances")
	UnreadyInstances          = intKey("unready_instances")
)
