name: "Set up environment"
description: "Set up the environment for the runner"
inputs:
  cachix_auth_token:
    description: "The Cachix auth token"
    required: true
outputs: {}
runs:
  using: "composite"
  steps:
    - name: Install Nix
      uses: nixbuild/nix-quick-install-action@v30

    - name: Cache Nix
      uses: cachix/cachix-action@v16
      with:
        name: skipper
        authToken: "${{ inputs.cachix_auth_token }}"

    - name: Set up direnv
      run: |
        curl -sfL https://direnv.net/install.sh | bash
        direnv allow
        direnv export gha >> "$GITHUB_ENV"
      shell: bash

    - name: Set up Go
      uses: useblacksmith/setup-go@v6

    - name: Install Go dependencies
      run: go mod download && go mod verify
      shell: bash

    - name: Set up Node.js
      uses: useblacksmith/setup-node@v5
      with:
        cache: "pnpm"

    - name: Install Node.js dependencies
      run: pnpm install
      shell: bash
