name: "Set up environment"
description: "Set up the environment for the runner"
inputs: {}
outputs: {}
runs:
  using: "composite"
  steps:
    - name: Install nix
      uses: DeterminateSystems/nix-installer-action@main

    - name: Cache nix
      uses: DeterminateSystems/magic-nix-cache-action@main

    - name: Set up nix environment
      run: |
        cd nix
        source <(nix print-dev-env --show-trace)
        echo "$PATH" >> "$GITHUB_PATH"
        echo "WORKSPACE_DIR=${{ github.workspace }}" >> "$GITHUB_ENV"
      shell: bash

    - name: Restore and cache go dependencies
      uses: actions/cache@v4
      with:
        key: setup-go-${{ runner.os }}-${{ hashFiles('go.sum') }}-${{ github.sha }}
        restore-keys: setup-go-${{ runner.os }}-
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod

    - name: Install go dependencies
      run: go mod download && go mod verify
      shell: bash

    - name: Restore and cache deno dependencies
      uses: actions/cache@v4
      with:
        key: setup-deno-${{ runner.os }}-${{ hashFiles('deno.lock') }}-${{ github.sha }}
        restore-keys: setup-deno-${{ runner.os }}-
        path: |
          ~/.deno
          ~/.cache/deno

    - name: Install deno dependencies
      run: deno install
      shell: bash
