name: "Set up Nix environment"
description: "Set up the Nix environment for the runner"
inputs:
  cachix_auth_token:
    description: "The Cachix auth token"
    required: true
outputs: {}
runs:
  using: "composite"
  steps:
    - name: Install Nix
      uses: nixbuild/nix-quick-install-action@v30

    - name: Cache Nix
      uses: cachix/cachix-action@v16
      with:
        name: skipper
        authToken: "${{ inputs.cachix_auth_token }}"

    - name: Set up Nix environment
      run: |
        cd nix
        source <(nix print-dev-env --show-trace)
        echo "$PATH" >> "$GITHUB_PATH"
        echo "WORKSPACE_DIR=${{ github.workspace }}" >> "$GITHUB_ENV"
      shell: bash

    - name: Restore and cache Go dependencies
      uses: useblacksmith/cache@v5
      with:
        key: setup-go-${{ runner.os }}-${{ hashFiles('go.sum') }}-${{ github.sha }}
        restore-keys: setup-go-${{ runner.os }}-
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod

    - name: Install Go dependencies
      run: go mod download && go mod verify
      shell: bash

    - name: Restore and cache Deno dependencies
      uses: useblacksmith/cache@v5
      with:
        key: setup-deno-${{ runner.os }}-${{ hashFiles('deno.lock') }}-${{ github.sha }}
        restore-keys: setup-deno-${{ runner.os }}-
        path: |
          ~/.deno
          ~/.cache/deno

    - name: Install Deno dependencies
      run: deno install
      shell: bash
