apiVersion: v1
kind: Namespace
metadata:
  name: example
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fusion
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fusion
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fusion
subjects:
  - kind: ServiceAccount
    name: fusion
    namespace: fusion-development
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
  namespace: example
spec:
  replicas: 1
  selector:
    matchLabels:
      name: example
      fusion/status: unassigned
  template:
    metadata:
      labels:
        name: example
        fusion/status: unassigned
        app.kubernetes.io/managed-by: fusion
    spec:
      containers:
        - name: example
          image: fusion-example:latest
          imagePullPolicy: Never
          ports:
            - name: http-port
              containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
