// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: controller.proto

package skipper

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request/Response messages for gRPC service
type GetInstanceRequest struct {
	state                           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Function             *Function              `protobuf:"bytes,1,opt,name=function"`
	xxx_hidden_ExcludeInstanceNames []string               `protobuf:"bytes,2,rep,name=exclude_instance_names,json=excludeInstanceNames"`
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *GetInstanceRequest) Reset() {
	*x = GetInstanceRequest{}
	mi := &file_controller_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstanceRequest) ProtoMessage() {}

func (x *GetInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetInstanceRequest) GetFunction() *Function {
	if x != nil {
		return x.xxx_hidden_Function
	}
	return nil
}

func (x *GetInstanceRequest) GetExcludeInstanceNames() []string {
	if x != nil {
		return x.xxx_hidden_ExcludeInstanceNames
	}
	return nil
}

func (x *GetInstanceRequest) SetFunction(v *Function) {
	x.xxx_hidden_Function = v
}

func (x *GetInstanceRequest) SetExcludeInstanceNames(v []string) {
	x.xxx_hidden_ExcludeInstanceNames = v
}

func (x *GetInstanceRequest) HasFunction() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Function != nil
}

func (x *GetInstanceRequest) ClearFunction() {
	x.xxx_hidden_Function = nil
}

type GetInstanceRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Function             *Function
	ExcludeInstanceNames []string
}

func (b0 GetInstanceRequest_builder) Build() *GetInstanceRequest {
	m0 := &GetInstanceRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Function = b.Function
	x.xxx_hidden_ExcludeInstanceNames = b.ExcludeInstanceNames
	return m0
}

type GetInstanceResponse struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Instance *Instance              `protobuf:"bytes,1,opt,name=instance"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetInstanceResponse) Reset() {
	*x = GetInstanceResponse{}
	mi := &file_controller_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstanceResponse) ProtoMessage() {}

func (x *GetInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetInstanceResponse) GetInstance() *Instance {
	if x != nil {
		return x.xxx_hidden_Instance
	}
	return nil
}

func (x *GetInstanceResponse) SetInstance(v *Instance) {
	x.xxx_hidden_Instance = v
}

func (x *GetInstanceResponse) HasInstance() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Instance != nil
}

func (x *GetInstanceResponse) ClearInstance() {
	x.xxx_hidden_Instance = nil
}

type GetInstanceResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Instance *Instance
}

func (b0 GetInstanceResponse_builder) Build() *GetInstanceResponse {
	m0 := &GetInstanceResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Instance = b.Instance
	return m0
}

type HeartbeatRequest struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RouterIp     *string                `protobuf:"bytes,1,opt,name=router_ip,json=routerIp"`
	xxx_hidden_Heartbeats   *[]*Heartbeat          `protobuf:"bytes,2,rep,name=heartbeats"`
	xxx_hidden_ForwardedFor []string               `protobuf:"bytes,3,rep,name=forwarded_for,json=forwardedFor"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_controller_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HeartbeatRequest) GetRouterIp() string {
	if x != nil {
		if x.xxx_hidden_RouterIp != nil {
			return *x.xxx_hidden_RouterIp
		}
		return ""
	}
	return ""
}

func (x *HeartbeatRequest) GetHeartbeats() []*Heartbeat {
	if x != nil {
		if x.xxx_hidden_Heartbeats != nil {
			return *x.xxx_hidden_Heartbeats
		}
	}
	return nil
}

func (x *HeartbeatRequest) GetForwardedFor() []string {
	if x != nil {
		return x.xxx_hidden_ForwardedFor
	}
	return nil
}

func (x *HeartbeatRequest) SetRouterIp(v string) {
	x.xxx_hidden_RouterIp = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *HeartbeatRequest) SetHeartbeats(v []*Heartbeat) {
	x.xxx_hidden_Heartbeats = &v
}

func (x *HeartbeatRequest) SetForwardedFor(v []string) {
	x.xxx_hidden_ForwardedFor = v
}

func (x *HeartbeatRequest) HasRouterIp() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *HeartbeatRequest) ClearRouterIp() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_RouterIp = nil
}

type HeartbeatRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RouterIp     *string
	Heartbeats   []*Heartbeat
	ForwardedFor []string
}

func (b0 HeartbeatRequest_builder) Build() *HeartbeatRequest {
	m0 := &HeartbeatRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.RouterIp != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_RouterIp = b.RouterIp
	}
	x.xxx_hidden_Heartbeats = &b.Heartbeats
	x.xxx_hidden_ForwardedFor = b.ForwardedFor
	return m0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_controller_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type HeartbeatResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 HeartbeatResponse_builder) Build() *HeartbeatResponse {
	m0 := &HeartbeatResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ScaleRequest struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Function         *Function              `protobuf:"bytes,1,opt,name=function"`
	xxx_hidden_DesiredInstances uint32                 `protobuf:"varint,2,opt,name=desired_instances,json=desiredInstances"`
	xxx_hidden_Reason           ScaleReason            `protobuf:"varint,3,opt,name=reason,enum=skipper.ScaleReason"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *ScaleRequest) Reset() {
	*x = ScaleRequest{}
	mi := &file_controller_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScaleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScaleRequest) ProtoMessage() {}

func (x *ScaleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ScaleRequest) GetFunction() *Function {
	if x != nil {
		return x.xxx_hidden_Function
	}
	return nil
}

func (x *ScaleRequest) GetDesiredInstances() uint32 {
	if x != nil {
		return x.xxx_hidden_DesiredInstances
	}
	return 0
}

func (x *ScaleRequest) GetReason() ScaleReason {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 2) {
			return x.xxx_hidden_Reason
		}
	}
	return ScaleReason_SCALE_REASON_UNSPECIFIED
}

func (x *ScaleRequest) SetFunction(v *Function) {
	x.xxx_hidden_Function = v
}

func (x *ScaleRequest) SetDesiredInstances(v uint32) {
	x.xxx_hidden_DesiredInstances = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *ScaleRequest) SetReason(v ScaleReason) {
	x.xxx_hidden_Reason = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *ScaleRequest) HasFunction() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Function != nil
}

func (x *ScaleRequest) HasDesiredInstances() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ScaleRequest) HasReason() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ScaleRequest) ClearFunction() {
	x.xxx_hidden_Function = nil
}

func (x *ScaleRequest) ClearDesiredInstances() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_DesiredInstances = 0
}

func (x *ScaleRequest) ClearReason() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Reason = ScaleReason_SCALE_REASON_UNSPECIFIED
}

type ScaleRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Function         *Function
	DesiredInstances *uint32
	Reason           *ScaleReason
}

func (b0 ScaleRequest_builder) Build() *ScaleRequest {
	m0 := &ScaleRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Function = b.Function
	if b.DesiredInstances != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_DesiredInstances = *b.DesiredInstances
	}
	if b.Reason != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Reason = *b.Reason
	}
	return m0
}

type ScaleResponse struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Instances *[]*Instance           `protobuf:"bytes,1,rep,name=instances"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ScaleResponse) Reset() {
	*x = ScaleResponse{}
	mi := &file_controller_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScaleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScaleResponse) ProtoMessage() {}

func (x *ScaleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ScaleResponse) GetInstances() []*Instance {
	if x != nil {
		if x.xxx_hidden_Instances != nil {
			return *x.xxx_hidden_Instances
		}
	}
	return nil
}

func (x *ScaleResponse) SetInstances(v []*Instance) {
	x.xxx_hidden_Instances = &v
}

type ScaleResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Instances []*Instance
}

func (b0 ScaleResponse_builder) Build() *ScaleResponse {
	m0 := &ScaleResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Instances = &b.Instances
	return m0
}

type ReplaceInstanceRequest struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Function     *Function              `protobuf:"bytes,1,opt,name=function"`
	xxx_hidden_InstanceName *string                `protobuf:"bytes,2,opt,name=instance_name,json=instanceName"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ReplaceInstanceRequest) Reset() {
	*x = ReplaceInstanceRequest{}
	mi := &file_controller_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplaceInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceInstanceRequest) ProtoMessage() {}

func (x *ReplaceInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ReplaceInstanceRequest) GetFunction() *Function {
	if x != nil {
		return x.xxx_hidden_Function
	}
	return nil
}

func (x *ReplaceInstanceRequest) GetInstanceName() string {
	if x != nil {
		if x.xxx_hidden_InstanceName != nil {
			return *x.xxx_hidden_InstanceName
		}
		return ""
	}
	return ""
}

func (x *ReplaceInstanceRequest) SetFunction(v *Function) {
	x.xxx_hidden_Function = v
}

func (x *ReplaceInstanceRequest) SetInstanceName(v string) {
	x.xxx_hidden_InstanceName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *ReplaceInstanceRequest) HasFunction() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Function != nil
}

func (x *ReplaceInstanceRequest) HasInstanceName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ReplaceInstanceRequest) ClearFunction() {
	x.xxx_hidden_Function = nil
}

func (x *ReplaceInstanceRequest) ClearInstanceName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_InstanceName = nil
}

type ReplaceInstanceRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Function     *Function
	InstanceName *string
}

func (b0 ReplaceInstanceRequest_builder) Build() *ReplaceInstanceRequest {
	m0 := &ReplaceInstanceRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Function = b.Function
	if b.InstanceName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_InstanceName = b.InstanceName
	}
	return m0
}

type ReplaceInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplaceInstanceResponse) Reset() {
	*x = ReplaceInstanceResponse{}
	mi := &file_controller_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplaceInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceInstanceResponse) ProtoMessage() {}

func (x *ReplaceInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ReplaceInstanceResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ReplaceInstanceResponse_builder) Build() *ReplaceInstanceResponse {
	m0 := &ReplaceInstanceResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_controller_proto protoreflect.FileDescriptor

const file_controller_proto_rawDesc = "" +
	"\n" +
	"\x10controller.proto\x12\askipper\x1a!google/protobuf/go_features.proto\x1a\vtypes.proto\"y\n" +
	"\x12GetInstanceRequest\x12-\n" +
	"\bfunction\x18\x01 \x01(\v2\x11.skipper.FunctionR\bfunction\x124\n" +
	"\x16exclude_instance_names\x18\x02 \x03(\tR\x14excludeInstanceNames\"D\n" +
	"\x13GetInstanceResponse\x12-\n" +
	"\binstance\x18\x01 \x01(\v2\x11.skipper.InstanceR\binstance\"\x88\x01\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\trouter_ip\x18\x01 \x01(\tR\brouterIp\x122\n" +
	"\n" +
	"heartbeats\x18\x02 \x03(\v2\x12.skipper.HeartbeatR\n" +
	"heartbeats\x12#\n" +
	"\rforwarded_for\x18\x03 \x03(\tR\fforwardedFor\"\x13\n" +
	"\x11HeartbeatResponse\"\x98\x01\n" +
	"\fScaleRequest\x12-\n" +
	"\bfunction\x18\x01 \x01(\v2\x11.skipper.FunctionR\bfunction\x12+\n" +
	"\x11desired_instances\x18\x02 \x01(\rR\x10desiredInstances\x12,\n" +
	"\x06reason\x18\x03 \x01(\x0e2\x14.skipper.ScaleReasonR\x06reason\"@\n" +
	"\rScaleResponse\x12/\n" +
	"\tinstances\x18\x01 \x03(\v2\x11.skipper.InstanceR\tinstances\"l\n" +
	"\x16ReplaceInstanceRequest\x12-\n" +
	"\bfunction\x18\x01 \x01(\v2\x11.skipper.FunctionR\bfunction\x12#\n" +
	"\rinstance_name\x18\x02 \x01(\tR\finstanceName\"\x19\n" +
	"\x17ReplaceInstanceResponse2\xaf\x02\n" +
	"\x11ControllerService\x12H\n" +
	"\vGetInstance\x12\x1b.skipper.GetInstanceRequest\x1a\x1c.skipper.GetInstanceResponse\x12B\n" +
	"\tHeartbeat\x12\x19.skipper.HeartbeatRequest\x1a\x1a.skipper.HeartbeatResponse\x126\n" +
	"\x05Scale\x12\x15.skipper.ScaleRequest\x1a\x16.skipper.ScaleResponse\x12T\n" +
	"\x0fReplaceInstance\x12\x1f.skipper.ReplaceInstanceRequest\x1a .skipper.ReplaceInstanceResponseB8Z.github.com/gadget-inc/skipper/internal/skipper\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_controller_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_controller_proto_goTypes = []any{
	(*GetInstanceRequest)(nil),      // 0: skipper.GetInstanceRequest
	(*GetInstanceResponse)(nil),     // 1: skipper.GetInstanceResponse
	(*HeartbeatRequest)(nil),        // 2: skipper.HeartbeatRequest
	(*HeartbeatResponse)(nil),       // 3: skipper.HeartbeatResponse
	(*ScaleRequest)(nil),            // 4: skipper.ScaleRequest
	(*ScaleResponse)(nil),           // 5: skipper.ScaleResponse
	(*ReplaceInstanceRequest)(nil),  // 6: skipper.ReplaceInstanceRequest
	(*ReplaceInstanceResponse)(nil), // 7: skipper.ReplaceInstanceResponse
	(*Function)(nil),                // 8: skipper.Function
	(*Instance)(nil),                // 9: skipper.Instance
	(*Heartbeat)(nil),               // 10: skipper.Heartbeat
	(ScaleReason)(0),                // 11: skipper.ScaleReason
}
var file_controller_proto_depIdxs = []int32{
	8,  // 0: skipper.GetInstanceRequest.function:type_name -> skipper.Function
	9,  // 1: skipper.GetInstanceResponse.instance:type_name -> skipper.Instance
	10, // 2: skipper.HeartbeatRequest.heartbeats:type_name -> skipper.Heartbeat
	8,  // 3: skipper.ScaleRequest.function:type_name -> skipper.Function
	11, // 4: skipper.ScaleRequest.reason:type_name -> skipper.ScaleReason
	9,  // 5: skipper.ScaleResponse.instances:type_name -> skipper.Instance
	8,  // 6: skipper.ReplaceInstanceRequest.function:type_name -> skipper.Function
	0,  // 7: skipper.ControllerService.GetInstance:input_type -> skipper.GetInstanceRequest
	2,  // 8: skipper.ControllerService.Heartbeat:input_type -> skipper.HeartbeatRequest
	4,  // 9: skipper.ControllerService.Scale:input_type -> skipper.ScaleRequest
	6,  // 10: skipper.ControllerService.ReplaceInstance:input_type -> skipper.ReplaceInstanceRequest
	1,  // 11: skipper.ControllerService.GetInstance:output_type -> skipper.GetInstanceResponse
	3,  // 12: skipper.ControllerService.Heartbeat:output_type -> skipper.HeartbeatResponse
	5,  // 13: skipper.ControllerService.Scale:output_type -> skipper.ScaleResponse
	7,  // 14: skipper.ControllerService.ReplaceInstance:output_type -> skipper.ReplaceInstanceResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_controller_proto_init() }
func file_controller_proto_init() {
	if File_controller_proto != nil {
		return
	}
	file_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_controller_proto_rawDesc), len(file_controller_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_controller_proto_goTypes,
		DependencyIndexes: file_controller_proto_depIdxs,
		MessageInfos:      file_controller_proto_msgTypes,
	}.Build()
	File_controller_proto = out.File
	file_controller_proto_goTypes = nil
	file_controller_proto_depIdxs = nil
}
