edition = "2023";

package skipper;

import "google/protobuf/go_features.proto";
import "google/protobuf/timestamp.proto";

option go_package = "github.com/gadget-inc/skipper/internal/skipper";
option features.(pb.go).api_level = API_OPAQUE;

message Scale {
  uint32 min_instances = 1;
  uint32 max_instances = 2;
  uint32 target_cpu_usage_milli = 3;
  uint32 target_memory_usage_mib = 4;
  uint32 target_in_flight_requests = 5;
}

message Function {
  string namespace = 1;
  string deployment = 2;
  string tenant = 3;
  string metadata = 4;
  Scale scale = 5;
  bool oneshot = 6;
}

message Instance {
  Function function = 1;
  string name = 2;
  string addr = 3;
  string replica_set = 4;
  google.protobuf.Timestamp assigned_at = 5;
  google.protobuf.Timestamp ready_at = 6;
  uint32 cpu_usage_milli = 7;
  uint32 memory_usage_mib = 8;
}

message Heartbeat {
  Function function = 1;
  google.protobuf.Timestamp timestamp = 2;
  uint32 in_flight_requests = 3;
}

enum ScaleReason {
  SCALE_REASON_UNSPECIFIED = 0;
  SCALE_REASON_CPU = 1;
  SCALE_REASON_HEARTBEAT_TIMEOUT = 2;
  SCALE_REASON_IN_FLIGHT_REQUESTS = 3;
  SCALE_REASON_MEMORY = 4;
  SCALE_REASON_NO_READY_INSTANCES = 5;
}

message ScaleMetric {
  string name = 1;
  double value = 2;
}

message ScaleDecision {
  uint32 desired_instances = 1;
  uint32 unclamped_desired_instances = 2;
  ScaleReason reason = 3;
  repeated ScaleMetric metrics = 4;
}
