// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: types.proto

package skipper

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScaleReason int32

const (
	ScaleReason_SCALE_REASON_UNSPECIFIED        ScaleReason = 0
	ScaleReason_SCALE_REASON_CPU                ScaleReason = 1
	ScaleReason_SCALE_REASON_HEARTBEAT_TIMEOUT  ScaleReason = 2
	ScaleReason_SCALE_REASON_IN_FLIGHT_REQUESTS ScaleReason = 3
	ScaleReason_SCALE_REASON_MEMORY             ScaleReason = 4
	ScaleReason_SCALE_REASON_NO_READY_INSTANCES ScaleReason = 5
)

// Enum value maps for ScaleReason.
var (
	ScaleReason_name = map[int32]string{
		0: "SCALE_REASON_UNSPECIFIED",
		1: "SCALE_REASON_CPU",
		2: "SCALE_REASON_HEARTBEAT_TIMEOUT",
		3: "SCALE_REASON_IN_FLIGHT_REQUESTS",
		4: "SCALE_REASON_MEMORY",
		5: "SCALE_REASON_NO_READY_INSTANCES",
	}
	ScaleReason_value = map[string]int32{
		"SCALE_REASON_UNSPECIFIED":        0,
		"SCALE_REASON_CPU":                1,
		"SCALE_REASON_HEARTBEAT_TIMEOUT":  2,
		"SCALE_REASON_IN_FLIGHT_REQUESTS": 3,
		"SCALE_REASON_MEMORY":             4,
		"SCALE_REASON_NO_READY_INSTANCES": 5,
	}
)

func (x ScaleReason) Enum() *ScaleReason {
	p := new(ScaleReason)
	*p = x
	return p
}

func (x ScaleReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScaleReason) Descriptor() protoreflect.EnumDescriptor {
	return file_types_proto_enumTypes[0].Descriptor()
}

func (ScaleReason) Type() protoreflect.EnumType {
	return &file_types_proto_enumTypes[0]
}

func (x ScaleReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type Scale struct {
	state                             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_MinInstances           uint32                 `protobuf:"varint,1,opt,name=min_instances,json=minInstances"`
	xxx_hidden_MaxInstances           uint32                 `protobuf:"varint,2,opt,name=max_instances,json=maxInstances"`
	xxx_hidden_TargetCpuUsageMilli    uint32                 `protobuf:"varint,3,opt,name=target_cpu_usage_milli,json=targetCpuUsageMilli"`
	xxx_hidden_TargetMemoryUsageMib   uint32                 `protobuf:"varint,4,opt,name=target_memory_usage_mib,json=targetMemoryUsageMib"`
	xxx_hidden_TargetInFlightRequests uint32                 `protobuf:"varint,5,opt,name=target_in_flight_requests,json=targetInFlightRequests"`
	XXX_raceDetectHookData            protoimpl.RaceDetectHookData
	XXX_presence                      [1]uint32
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *Scale) Reset() {
	*x = Scale{}
	mi := &file_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scale) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scale) ProtoMessage() {}

func (x *Scale) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Scale) GetMinInstances() uint32 {
	if x != nil {
		return x.xxx_hidden_MinInstances
	}
	return 0
}

func (x *Scale) GetMaxInstances() uint32 {
	if x != nil {
		return x.xxx_hidden_MaxInstances
	}
	return 0
}

func (x *Scale) GetTargetCpuUsageMilli() uint32 {
	if x != nil {
		return x.xxx_hidden_TargetCpuUsageMilli
	}
	return 0
}

func (x *Scale) GetTargetMemoryUsageMib() uint32 {
	if x != nil {
		return x.xxx_hidden_TargetMemoryUsageMib
	}
	return 0
}

func (x *Scale) GetTargetInFlightRequests() uint32 {
	if x != nil {
		return x.xxx_hidden_TargetInFlightRequests
	}
	return 0
}

func (x *Scale) SetMinInstances(v uint32) {
	x.xxx_hidden_MinInstances = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *Scale) SetMaxInstances(v uint32) {
	x.xxx_hidden_MaxInstances = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *Scale) SetTargetCpuUsageMilli(v uint32) {
	x.xxx_hidden_TargetCpuUsageMilli = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *Scale) SetTargetMemoryUsageMib(v uint32) {
	x.xxx_hidden_TargetMemoryUsageMib = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *Scale) SetTargetInFlightRequests(v uint32) {
	x.xxx_hidden_TargetInFlightRequests = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *Scale) HasMinInstances() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Scale) HasMaxInstances() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Scale) HasTargetCpuUsageMilli() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Scale) HasTargetMemoryUsageMib() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Scale) HasTargetInFlightRequests() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Scale) ClearMinInstances() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_MinInstances = 0
}

func (x *Scale) ClearMaxInstances() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_MaxInstances = 0
}

func (x *Scale) ClearTargetCpuUsageMilli() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_TargetCpuUsageMilli = 0
}

func (x *Scale) ClearTargetMemoryUsageMib() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_TargetMemoryUsageMib = 0
}

func (x *Scale) ClearTargetInFlightRequests() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_TargetInFlightRequests = 0
}

type Scale_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	MinInstances           *uint32
	MaxInstances           *uint32
	TargetCpuUsageMilli    *uint32
	TargetMemoryUsageMib   *uint32
	TargetInFlightRequests *uint32
}

func (b0 Scale_builder) Build() *Scale {
	m0 := &Scale{}
	b, x := &b0, m0
	_, _ = b, x
	if b.MinInstances != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_MinInstances = *b.MinInstances
	}
	if b.MaxInstances != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_MaxInstances = *b.MaxInstances
	}
	if b.TargetCpuUsageMilli != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_TargetCpuUsageMilli = *b.TargetCpuUsageMilli
	}
	if b.TargetMemoryUsageMib != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_TargetMemoryUsageMib = *b.TargetMemoryUsageMib
	}
	if b.TargetInFlightRequests != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_TargetInFlightRequests = *b.TargetInFlightRequests
	}
	return m0
}

type Function struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Namespace   *string                `protobuf:"bytes,1,opt,name=namespace"`
	xxx_hidden_Deployment  *string                `protobuf:"bytes,2,opt,name=deployment"`
	xxx_hidden_Tenant      *string                `protobuf:"bytes,3,opt,name=tenant"`
	xxx_hidden_Metadata    *string                `protobuf:"bytes,4,opt,name=metadata"`
	xxx_hidden_Scale       *Scale                 `protobuf:"bytes,5,opt,name=scale"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Function) Reset() {
	*x = Function{}
	mi := &file_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Function) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Function) ProtoMessage() {}

func (x *Function) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Function) GetNamespace() string {
	if x != nil {
		if x.xxx_hidden_Namespace != nil {
			return *x.xxx_hidden_Namespace
		}
		return ""
	}
	return ""
}

func (x *Function) GetDeployment() string {
	if x != nil {
		if x.xxx_hidden_Deployment != nil {
			return *x.xxx_hidden_Deployment
		}
		return ""
	}
	return ""
}

func (x *Function) GetTenant() string {
	if x != nil {
		if x.xxx_hidden_Tenant != nil {
			return *x.xxx_hidden_Tenant
		}
		return ""
	}
	return ""
}

func (x *Function) GetMetadata() string {
	if x != nil {
		if x.xxx_hidden_Metadata != nil {
			return *x.xxx_hidden_Metadata
		}
		return ""
	}
	return ""
}

func (x *Function) GetScale() *Scale {
	if x != nil {
		return x.xxx_hidden_Scale
	}
	return nil
}

func (x *Function) SetNamespace(v string) {
	x.xxx_hidden_Namespace = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *Function) SetDeployment(v string) {
	x.xxx_hidden_Deployment = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *Function) SetTenant(v string) {
	x.xxx_hidden_Tenant = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *Function) SetMetadata(v string) {
	x.xxx_hidden_Metadata = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *Function) SetScale(v *Scale) {
	x.xxx_hidden_Scale = v
}

func (x *Function) HasNamespace() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Function) HasDeployment() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Function) HasTenant() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Function) HasMetadata() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Function) HasScale() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Scale != nil
}

func (x *Function) ClearNamespace() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Namespace = nil
}

func (x *Function) ClearDeployment() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Deployment = nil
}

func (x *Function) ClearTenant() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Tenant = nil
}

func (x *Function) ClearMetadata() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Metadata = nil
}

func (x *Function) ClearScale() {
	x.xxx_hidden_Scale = nil
}

type Function_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Namespace  *string
	Deployment *string
	Tenant     *string
	Metadata   *string
	Scale      *Scale
}

func (b0 Function_builder) Build() *Function {
	m0 := &Function{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Namespace != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_Namespace = b.Namespace
	}
	if b.Deployment != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_Deployment = b.Deployment
	}
	if b.Tenant != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_Tenant = b.Tenant
	}
	if b.Metadata != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_Metadata = b.Metadata
	}
	x.xxx_hidden_Scale = b.Scale
	return m0
}

type Instance struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Function       *Function              `protobuf:"bytes,1,opt,name=function"`
	xxx_hidden_Name           *string                `protobuf:"bytes,2,opt,name=name"`
	xxx_hidden_Addr           *string                `protobuf:"bytes,3,opt,name=addr"`
	xxx_hidden_ReplicaSet     *string                `protobuf:"bytes,4,opt,name=replica_set,json=replicaSet"`
	xxx_hidden_AssignedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=assigned_at,json=assignedAt"`
	xxx_hidden_ReadyAt        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=ready_at,json=readyAt"`
	xxx_hidden_CpuUsageMilli  uint32                 `protobuf:"varint,7,opt,name=cpu_usage_milli,json=cpuUsageMilli"`
	xxx_hidden_MemoryUsageMib uint32                 `protobuf:"varint,8,opt,name=memory_usage_mib,json=memoryUsageMib"`
	XXX_raceDetectHookData    protoimpl.RaceDetectHookData
	XXX_presence              [1]uint32
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *Instance) Reset() {
	*x = Instance{}
	mi := &file_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instance) ProtoMessage() {}

func (x *Instance) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Instance) GetFunction() *Function {
	if x != nil {
		return x.xxx_hidden_Function
	}
	return nil
}

func (x *Instance) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *Instance) GetAddr() string {
	if x != nil {
		if x.xxx_hidden_Addr != nil {
			return *x.xxx_hidden_Addr
		}
		return ""
	}
	return ""
}

func (x *Instance) GetReplicaSet() string {
	if x != nil {
		if x.xxx_hidden_ReplicaSet != nil {
			return *x.xxx_hidden_ReplicaSet
		}
		return ""
	}
	return ""
}

func (x *Instance) GetAssignedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_AssignedAt
	}
	return nil
}

func (x *Instance) GetReadyAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_ReadyAt
	}
	return nil
}

func (x *Instance) GetCpuUsageMilli() uint32 {
	if x != nil {
		return x.xxx_hidden_CpuUsageMilli
	}
	return 0
}

func (x *Instance) GetMemoryUsageMib() uint32 {
	if x != nil {
		return x.xxx_hidden_MemoryUsageMib
	}
	return 0
}

func (x *Instance) SetFunction(v *Function) {
	x.xxx_hidden_Function = v
}

func (x *Instance) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 8)
}

func (x *Instance) SetAddr(v string) {
	x.xxx_hidden_Addr = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 8)
}

func (x *Instance) SetReplicaSet(v string) {
	x.xxx_hidden_ReplicaSet = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 8)
}

func (x *Instance) SetAssignedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_AssignedAt = v
}

func (x *Instance) SetReadyAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_ReadyAt = v
}

func (x *Instance) SetCpuUsageMilli(v uint32) {
	x.xxx_hidden_CpuUsageMilli = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 8)
}

func (x *Instance) SetMemoryUsageMib(v uint32) {
	x.xxx_hidden_MemoryUsageMib = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 8)
}

func (x *Instance) HasFunction() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Function != nil
}

func (x *Instance) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Instance) HasAddr() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Instance) HasReplicaSet() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Instance) HasAssignedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_AssignedAt != nil
}

func (x *Instance) HasReadyAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ReadyAt != nil
}

func (x *Instance) HasCpuUsageMilli() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *Instance) HasMemoryUsageMib() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *Instance) ClearFunction() {
	x.xxx_hidden_Function = nil
}

func (x *Instance) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Name = nil
}

func (x *Instance) ClearAddr() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Addr = nil
}

func (x *Instance) ClearReplicaSet() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_ReplicaSet = nil
}

func (x *Instance) ClearAssignedAt() {
	x.xxx_hidden_AssignedAt = nil
}

func (x *Instance) ClearReadyAt() {
	x.xxx_hidden_ReadyAt = nil
}

func (x *Instance) ClearCpuUsageMilli() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_CpuUsageMilli = 0
}

func (x *Instance) ClearMemoryUsageMib() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_MemoryUsageMib = 0
}

type Instance_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Function       *Function
	Name           *string
	Addr           *string
	ReplicaSet     *string
	AssignedAt     *timestamppb.Timestamp
	ReadyAt        *timestamppb.Timestamp
	CpuUsageMilli  *uint32
	MemoryUsageMib *uint32
}

func (b0 Instance_builder) Build() *Instance {
	m0 := &Instance{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Function = b.Function
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 8)
		x.xxx_hidden_Name = b.Name
	}
	if b.Addr != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 8)
		x.xxx_hidden_Addr = b.Addr
	}
	if b.ReplicaSet != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 8)
		x.xxx_hidden_ReplicaSet = b.ReplicaSet
	}
	x.xxx_hidden_AssignedAt = b.AssignedAt
	x.xxx_hidden_ReadyAt = b.ReadyAt
	if b.CpuUsageMilli != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 8)
		x.xxx_hidden_CpuUsageMilli = *b.CpuUsageMilli
	}
	if b.MemoryUsageMib != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 8)
		x.xxx_hidden_MemoryUsageMib = *b.MemoryUsageMib
	}
	return m0
}

type Heartbeat struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Function         *Function              `protobuf:"bytes,1,opt,name=function"`
	xxx_hidden_Timestamp        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp"`
	xxx_hidden_InFlightRequests uint32                 `protobuf:"varint,3,opt,name=in_flight_requests,json=inFlightRequests"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Heartbeat) GetFunction() *Function {
	if x != nil {
		return x.xxx_hidden_Function
	}
	return nil
}

func (x *Heartbeat) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Timestamp
	}
	return nil
}

func (x *Heartbeat) GetInFlightRequests() uint32 {
	if x != nil {
		return x.xxx_hidden_InFlightRequests
	}
	return 0
}

func (x *Heartbeat) SetFunction(v *Function) {
	x.xxx_hidden_Function = v
}

func (x *Heartbeat) SetTimestamp(v *timestamppb.Timestamp) {
	x.xxx_hidden_Timestamp = v
}

func (x *Heartbeat) SetInFlightRequests(v uint32) {
	x.xxx_hidden_InFlightRequests = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *Heartbeat) HasFunction() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Function != nil
}

func (x *Heartbeat) HasTimestamp() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Timestamp != nil
}

func (x *Heartbeat) HasInFlightRequests() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Heartbeat) ClearFunction() {
	x.xxx_hidden_Function = nil
}

func (x *Heartbeat) ClearTimestamp() {
	x.xxx_hidden_Timestamp = nil
}

func (x *Heartbeat) ClearInFlightRequests() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_InFlightRequests = 0
}

type Heartbeat_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Function         *Function
	Timestamp        *timestamppb.Timestamp
	InFlightRequests *uint32
}

func (b0 Heartbeat_builder) Build() *Heartbeat {
	m0 := &Heartbeat{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Function = b.Function
	x.xxx_hidden_Timestamp = b.Timestamp
	if b.InFlightRequests != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_InFlightRequests = *b.InFlightRequests
	}
	return m0
}

type ScaleMetric struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        *string                `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_Value       float64                `protobuf:"fixed64,2,opt,name=value"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ScaleMetric) Reset() {
	*x = ScaleMetric{}
	mi := &file_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScaleMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScaleMetric) ProtoMessage() {}

func (x *ScaleMetric) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ScaleMetric) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *ScaleMetric) GetValue() float64 {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return 0
}

func (x *ScaleMetric) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *ScaleMetric) SetValue(v float64) {
	x.xxx_hidden_Value = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *ScaleMetric) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ScaleMetric) HasValue() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ScaleMetric) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

func (x *ScaleMetric) ClearValue() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Value = 0
}

type ScaleMetric_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name  *string
	Value *float64
}

func (b0 ScaleMetric_builder) Build() *ScaleMetric {
	m0 := &ScaleMetric{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Name = b.Name
	}
	if b.Value != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Value = *b.Value
	}
	return m0
}

type ScaleDecision struct {
	state                                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_DesiredInstances          uint32                 `protobuf:"varint,1,opt,name=desired_instances,json=desiredInstances"`
	xxx_hidden_UnclampedDesiredInstances uint32                 `protobuf:"varint,2,opt,name=unclamped_desired_instances,json=unclampedDesiredInstances"`
	xxx_hidden_Reason                    ScaleReason            `protobuf:"varint,3,opt,name=reason,enum=skipper.ScaleReason"`
	xxx_hidden_Metrics                   *[]*ScaleMetric        `protobuf:"bytes,4,rep,name=metrics"`
	XXX_raceDetectHookData               protoimpl.RaceDetectHookData
	XXX_presence                         [1]uint32
	unknownFields                        protoimpl.UnknownFields
	sizeCache                            protoimpl.SizeCache
}

func (x *ScaleDecision) Reset() {
	*x = ScaleDecision{}
	mi := &file_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScaleDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScaleDecision) ProtoMessage() {}

func (x *ScaleDecision) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ScaleDecision) GetDesiredInstances() uint32 {
	if x != nil {
		return x.xxx_hidden_DesiredInstances
	}
	return 0
}

func (x *ScaleDecision) GetUnclampedDesiredInstances() uint32 {
	if x != nil {
		return x.xxx_hidden_UnclampedDesiredInstances
	}
	return 0
}

func (x *ScaleDecision) GetReason() ScaleReason {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 2) {
			return x.xxx_hidden_Reason
		}
	}
	return ScaleReason_SCALE_REASON_UNSPECIFIED
}

func (x *ScaleDecision) GetMetrics() []*ScaleMetric {
	if x != nil {
		if x.xxx_hidden_Metrics != nil {
			return *x.xxx_hidden_Metrics
		}
	}
	return nil
}

func (x *ScaleDecision) SetDesiredInstances(v uint32) {
	x.xxx_hidden_DesiredInstances = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *ScaleDecision) SetUnclampedDesiredInstances(v uint32) {
	x.xxx_hidden_UnclampedDesiredInstances = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *ScaleDecision) SetReason(v ScaleReason) {
	x.xxx_hidden_Reason = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *ScaleDecision) SetMetrics(v []*ScaleMetric) {
	x.xxx_hidden_Metrics = &v
}

func (x *ScaleDecision) HasDesiredInstances() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ScaleDecision) HasUnclampedDesiredInstances() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ScaleDecision) HasReason() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ScaleDecision) ClearDesiredInstances() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_DesiredInstances = 0
}

func (x *ScaleDecision) ClearUnclampedDesiredInstances() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_UnclampedDesiredInstances = 0
}

func (x *ScaleDecision) ClearReason() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Reason = ScaleReason_SCALE_REASON_UNSPECIFIED
}

type ScaleDecision_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	DesiredInstances          *uint32
	UnclampedDesiredInstances *uint32
	Reason                    *ScaleReason
	Metrics                   []*ScaleMetric
}

func (b0 ScaleDecision_builder) Build() *ScaleDecision {
	m0 := &ScaleDecision{}
	b, x := &b0, m0
	_, _ = b, x
	if b.DesiredInstances != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_DesiredInstances = *b.DesiredInstances
	}
	if b.UnclampedDesiredInstances != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_UnclampedDesiredInstances = *b.UnclampedDesiredInstances
	}
	if b.Reason != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Reason = *b.Reason
	}
	x.xxx_hidden_Metrics = &b.Metrics
	return m0
}

var File_types_proto protoreflect.FileDescriptor

const file_types_proto_rawDesc = "" +
	"\n" +
	"\vtypes.proto\x12\askipper\x1a!google/protobuf/go_features.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf8\x01\n" +
	"\x05Scale\x12#\n" +
	"\rmin_instances\x18\x01 \x01(\rR\fminInstances\x12#\n" +
	"\rmax_instances\x18\x02 \x01(\rR\fmaxInstances\x123\n" +
	"\x16target_cpu_usage_milli\x18\x03 \x01(\rR\x13targetCpuUsageMilli\x125\n" +
	"\x17target_memory_usage_mib\x18\x04 \x01(\rR\x14targetMemoryUsageMib\x129\n" +
	"\x19target_in_flight_requests\x18\x05 \x01(\rR\x16targetInFlightRequests\"\xa2\x01\n" +
	"\bFunction\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"deployment\x18\x02 \x01(\tR\n" +
	"deployment\x12\x16\n" +
	"\x06tenant\x18\x03 \x01(\tR\x06tenant\x12\x1a\n" +
	"\bmetadata\x18\x04 \x01(\tR\bmetadata\x12$\n" +
	"\x05scale\x18\x05 \x01(\v2\x0e.skipper.ScaleR\x05scale\"\xc8\x02\n" +
	"\bInstance\x12-\n" +
	"\bfunction\x18\x01 \x01(\v2\x11.skipper.FunctionR\bfunction\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04addr\x18\x03 \x01(\tR\x04addr\x12\x1f\n" +
	"\vreplica_set\x18\x04 \x01(\tR\n" +
	"replicaSet\x12;\n" +
	"\vassigned_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"assignedAt\x125\n" +
	"\bready_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\areadyAt\x12&\n" +
	"\x0fcpu_usage_milli\x18\a \x01(\rR\rcpuUsageMilli\x12(\n" +
	"\x10memory_usage_mib\x18\b \x01(\rR\x0ememoryUsageMib\"\xa2\x01\n" +
	"\tHeartbeat\x12-\n" +
	"\bfunction\x18\x01 \x01(\v2\x11.skipper.FunctionR\bfunction\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12,\n" +
	"\x12in_flight_requests\x18\x03 \x01(\rR\x10inFlightRequests\"7\n" +
	"\vScaleMetric\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\"\xda\x01\n" +
	"\rScaleDecision\x12+\n" +
	"\x11desired_instances\x18\x01 \x01(\rR\x10desiredInstances\x12>\n" +
	"\x1bunclamped_desired_instances\x18\x02 \x01(\rR\x19unclampedDesiredInstances\x12,\n" +
	"\x06reason\x18\x03 \x01(\x0e2\x14.skipper.ScaleReasonR\x06reason\x12.\n" +
	"\ametrics\x18\x04 \x03(\v2\x14.skipper.ScaleMetricR\ametrics*\xc8\x01\n" +
	"\vScaleReason\x12\x1c\n" +
	"\x18SCALE_REASON_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10SCALE_REASON_CPU\x10\x01\x12\"\n" +
	"\x1eSCALE_REASON_HEARTBEAT_TIMEOUT\x10\x02\x12#\n" +
	"\x1fSCALE_REASON_IN_FLIGHT_REQUESTS\x10\x03\x12\x17\n" +
	"\x13SCALE_REASON_MEMORY\x10\x04\x12#\n" +
	"\x1fSCALE_REASON_NO_READY_INSTANCES\x10\x05B8Z.github.com/gadget-inc/skipper/internal/skipper\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_types_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_types_proto_goTypes = []any{
	(ScaleReason)(0),              // 0: skipper.ScaleReason
	(*Scale)(nil),                 // 1: skipper.Scale
	(*Function)(nil),              // 2: skipper.Function
	(*Instance)(nil),              // 3: skipper.Instance
	(*Heartbeat)(nil),             // 4: skipper.Heartbeat
	(*ScaleMetric)(nil),           // 5: skipper.ScaleMetric
	(*ScaleDecision)(nil),         // 6: skipper.ScaleDecision
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_types_proto_depIdxs = []int32{
	1, // 0: skipper.Function.scale:type_name -> skipper.Scale
	2, // 1: skipper.Instance.function:type_name -> skipper.Function
	7, // 2: skipper.Instance.assigned_at:type_name -> google.protobuf.Timestamp
	7, // 3: skipper.Instance.ready_at:type_name -> google.protobuf.Timestamp
	2, // 4: skipper.Heartbeat.function:type_name -> skipper.Function
	7, // 5: skipper.Heartbeat.timestamp:type_name -> google.protobuf.Timestamp
	0, // 6: skipper.ScaleDecision.reason:type_name -> skipper.ScaleReason
	5, // 7: skipper.ScaleDecision.metrics:type_name -> skipper.ScaleMetric
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_types_proto_init() }
func file_types_proto_init() {
	if File_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_proto_rawDesc), len(file_types_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_proto_goTypes,
		DependencyIndexes: file_types_proto_depIdxs,
		EnumInfos:         file_types_proto_enumTypes,
		MessageInfos:      file_types_proto_msgTypes,
	}.Build()
	File_types_proto = out.File
	file_types_proto_goTypes = nil
	file_types_proto_depIdxs = nil
}
