---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fusion-controller
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods"]
    verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fusion-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fusion-controller
subjects:
  - kind: ServiceAccount
    name: fusion-controller
    namespace: fusion-development
