name: "Set up Docker"
description: "Set up Docker for the runner"
inputs: {}
outputs: {}
runs:
  using: "composite"
  steps:
    - name: Set up Docker
      uses: useblacksmith/setup-docker-builder@v1
