// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: function.proto

package function

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Function struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Namespace  string                 `protobuf:"bytes,1,opt,name=namespace,proto3"`
	xxx_hidden_Deployment string                 `protobuf:"bytes,2,opt,name=deployment,proto3"`
	xxx_hidden_Tenant     string                 `protobuf:"bytes,3,opt,name=tenant,proto3"`
	xxx_hidden_Metadata   string                 `protobuf:"bytes,4,opt,name=metadata,proto3"`
	xxx_hidden_Scale      *Scale                 `protobuf:"bytes,5,opt,name=scale,proto3"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Function) Reset() {
	*x = Function{}
	mi := &file_function_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Function) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Function) ProtoMessage() {}

func (x *Function) ProtoReflect() protoreflect.Message {
	mi := &file_function_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Function) GetNamespace() string {
	if x != nil {
		return x.xxx_hidden_Namespace
	}
	return ""
}

func (x *Function) GetDeployment() string {
	if x != nil {
		return x.xxx_hidden_Deployment
	}
	return ""
}

func (x *Function) GetTenant() string {
	if x != nil {
		return x.xxx_hidden_Tenant
	}
	return ""
}

func (x *Function) GetMetadata() string {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return ""
}

func (x *Function) GetScale() *Scale {
	if x != nil {
		return x.xxx_hidden_Scale
	}
	return nil
}

func (x *Function) SetNamespace(v string) {
	x.xxx_hidden_Namespace = v
}

func (x *Function) SetDeployment(v string) {
	x.xxx_hidden_Deployment = v
}

func (x *Function) SetTenant(v string) {
	x.xxx_hidden_Tenant = v
}

func (x *Function) SetMetadata(v string) {
	x.xxx_hidden_Metadata = v
}

func (x *Function) SetScale(v *Scale) {
	x.xxx_hidden_Scale = v
}

func (x *Function) HasScale() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Scale != nil
}

func (x *Function) ClearScale() {
	x.xxx_hidden_Scale = nil
}

type Function_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Namespace  string
	Deployment string
	Tenant     string
	Metadata   string
	Scale      *Scale
}

func (b0 Function_builder) Build() *Function {
	m0 := &Function{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Namespace = b.Namespace
	x.xxx_hidden_Deployment = b.Deployment
	x.xxx_hidden_Tenant = b.Tenant
	x.xxx_hidden_Metadata = b.Metadata
	x.xxx_hidden_Scale = b.Scale
	return m0
}

var File_function_proto protoreflect.FileDescriptor

const file_function_proto_rawDesc = "" +
	"\n" +
	"\x0efunction.proto\x12\bfunction\x1a\vscale.proto\"\xa3\x01\n" +
	"\bFunction\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"deployment\x18\x02 \x01(\tR\n" +
	"deployment\x12\x16\n" +
	"\x06tenant\x18\x03 \x01(\tR\x06tenant\x12\x1a\n" +
	"\bmetadata\x18\x04 \x01(\tR\bmetadata\x12%\n" +
	"\x05scale\x18\x05 \x01(\v2\x0f.function.ScaleR\x05scaleB1Z/github.com/gadget-inc/skipper/internal/functionb\x06proto3"

var file_function_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_function_proto_goTypes = []any{
	(*Function)(nil), // 0: function.Function
	(*Scale)(nil),    // 1: function.Scale
}
var file_function_proto_depIdxs = []int32{
	1, // 0: function.Function.scale:type_name -> function.Scale
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_function_proto_init() }
func file_function_proto_init() {
	if File_function_proto != nil {
		return
	}
	file_scale_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_function_proto_rawDesc), len(file_function_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_function_proto_goTypes,
		DependencyIndexes: file_function_proto_depIdxs,
		MessageInfos:      file_function_proto_msgTypes,
	}.Build()
	File_function_proto = out.File
	file_function_proto_goTypes = nil
	file_function_proto_depIdxs = nil
}
