// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: heartbeat.proto

package function

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Heartbeat struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Function         *Function              `protobuf:"bytes,1,opt,name=function,proto3"`
	xxx_hidden_Timestamp        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3"`
	xxx_hidden_InFlightRequests uint32                 `protobuf:"varint,3,opt,name=in_flight_requests,json=inFlightRequests,proto3"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_heartbeat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_heartbeat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Heartbeat) GetFunction() *Function {
	if x != nil {
		return x.xxx_hidden_Function
	}
	return nil
}

func (x *Heartbeat) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Timestamp
	}
	return nil
}

func (x *Heartbeat) GetInFlightRequests() uint32 {
	if x != nil {
		return x.xxx_hidden_InFlightRequests
	}
	return 0
}

func (x *Heartbeat) SetFunction(v *Function) {
	x.xxx_hidden_Function = v
}

func (x *Heartbeat) SetTimestamp(v *timestamppb.Timestamp) {
	x.xxx_hidden_Timestamp = v
}

func (x *Heartbeat) SetInFlightRequests(v uint32) {
	x.xxx_hidden_InFlightRequests = v
}

func (x *Heartbeat) HasFunction() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Function != nil
}

func (x *Heartbeat) HasTimestamp() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Timestamp != nil
}

func (x *Heartbeat) ClearFunction() {
	x.xxx_hidden_Function = nil
}

func (x *Heartbeat) ClearTimestamp() {
	x.xxx_hidden_Timestamp = nil
}

type Heartbeat_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Function         *Function
	Timestamp        *timestamppb.Timestamp
	InFlightRequests uint32
}

func (b0 Heartbeat_builder) Build() *Heartbeat {
	m0 := &Heartbeat{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Function = b.Function
	x.xxx_hidden_Timestamp = b.Timestamp
	x.xxx_hidden_InFlightRequests = b.InFlightRequests
	return m0
}

var File_heartbeat_proto protoreflect.FileDescriptor

const file_heartbeat_proto_rawDesc = "" +
	"\n" +
	"\x0fheartbeat.proto\x12\bfunction\x1a\x0efunction.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa3\x01\n" +
	"\tHeartbeat\x12.\n" +
	"\bfunction\x18\x01 \x01(\v2\x12.function.FunctionR\bfunction\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12,\n" +
	"\x12in_flight_requests\x18\x03 \x01(\rR\x10inFlightRequestsB1Z/github.com/gadget-inc/skipper/internal/functionb\x06proto3"

var file_heartbeat_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_heartbeat_proto_goTypes = []any{
	(*Heartbeat)(nil),             // 0: function.Heartbeat
	(*Function)(nil),              // 1: function.Function
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_heartbeat_proto_depIdxs = []int32{
	1, // 0: function.Heartbeat.function:type_name -> function.Function
	2, // 1: function.Heartbeat.timestamp:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_heartbeat_proto_init() }
func file_heartbeat_proto_init() {
	if File_heartbeat_proto != nil {
		return
	}
	file_function_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_heartbeat_proto_rawDesc), len(file_heartbeat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_heartbeat_proto_goTypes,
		DependencyIndexes: file_heartbeat_proto_depIdxs,
		MessageInfos:      file_heartbeat_proto_msgTypes,
	}.Build()
	File_heartbeat_proto = out.File
	file_heartbeat_proto_goTypes = nil
	file_heartbeat_proto_depIdxs = nil
}
