// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: instance.proto

package function

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Instance struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Function       *Function              `protobuf:"bytes,1,opt,name=function,proto3"`
	xxx_hidden_Name           string                 `protobuf:"bytes,2,opt,name=name,proto3"`
	xxx_hidden_Addr           string                 `protobuf:"bytes,3,opt,name=addr,proto3"`
	xxx_hidden_ReplicaSet     string                 `protobuf:"bytes,4,opt,name=replica_set,json=replicaSet,proto3"`
	xxx_hidden_AssignedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=assigned_at,json=assignedAt,proto3"`
	xxx_hidden_ReadyAt        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=ready_at,json=readyAt,proto3"`
	xxx_hidden_CpuUsageMilli  uint32                 `protobuf:"varint,7,opt,name=cpu_usage_milli,json=cpuUsageMilli,proto3"`
	xxx_hidden_MemoryUsageMib uint32                 `protobuf:"varint,8,opt,name=memory_usage_mib,json=memoryUsageMib,proto3"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *Instance) Reset() {
	*x = Instance{}
	mi := &file_instance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instance) ProtoMessage() {}

func (x *Instance) ProtoReflect() protoreflect.Message {
	mi := &file_instance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Instance) GetFunction() *Function {
	if x != nil {
		return x.xxx_hidden_Function
	}
	return nil
}

func (x *Instance) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *Instance) GetAddr() string {
	if x != nil {
		return x.xxx_hidden_Addr
	}
	return ""
}

func (x *Instance) GetReplicaSet() string {
	if x != nil {
		return x.xxx_hidden_ReplicaSet
	}
	return ""
}

func (x *Instance) GetAssignedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_AssignedAt
	}
	return nil
}

func (x *Instance) GetReadyAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_ReadyAt
	}
	return nil
}

func (x *Instance) GetCpuUsageMilli() uint32 {
	if x != nil {
		return x.xxx_hidden_CpuUsageMilli
	}
	return 0
}

func (x *Instance) GetMemoryUsageMib() uint32 {
	if x != nil {
		return x.xxx_hidden_MemoryUsageMib
	}
	return 0
}

func (x *Instance) SetFunction(v *Function) {
	x.xxx_hidden_Function = v
}

func (x *Instance) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *Instance) SetAddr(v string) {
	x.xxx_hidden_Addr = v
}

func (x *Instance) SetReplicaSet(v string) {
	x.xxx_hidden_ReplicaSet = v
}

func (x *Instance) SetAssignedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_AssignedAt = v
}

func (x *Instance) SetReadyAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_ReadyAt = v
}

func (x *Instance) SetCpuUsageMilli(v uint32) {
	x.xxx_hidden_CpuUsageMilli = v
}

func (x *Instance) SetMemoryUsageMib(v uint32) {
	x.xxx_hidden_MemoryUsageMib = v
}

func (x *Instance) HasFunction() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Function != nil
}

func (x *Instance) HasAssignedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_AssignedAt != nil
}

func (x *Instance) HasReadyAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ReadyAt != nil
}

func (x *Instance) ClearFunction() {
	x.xxx_hidden_Function = nil
}

func (x *Instance) ClearAssignedAt() {
	x.xxx_hidden_AssignedAt = nil
}

func (x *Instance) ClearReadyAt() {
	x.xxx_hidden_ReadyAt = nil
}

type Instance_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Function       *Function
	Name           string
	Addr           string
	ReplicaSet     string
	AssignedAt     *timestamppb.Timestamp
	ReadyAt        *timestamppb.Timestamp
	CpuUsageMilli  uint32
	MemoryUsageMib uint32
}

func (b0 Instance_builder) Build() *Instance {
	m0 := &Instance{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Function = b.Function
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Addr = b.Addr
	x.xxx_hidden_ReplicaSet = b.ReplicaSet
	x.xxx_hidden_AssignedAt = b.AssignedAt
	x.xxx_hidden_ReadyAt = b.ReadyAt
	x.xxx_hidden_CpuUsageMilli = b.CpuUsageMilli
	x.xxx_hidden_MemoryUsageMib = b.MemoryUsageMib
	return m0
}

var File_instance_proto protoreflect.FileDescriptor

const file_instance_proto_rawDesc = "" +
	"\n" +
	"\x0einstance.proto\x12\bfunction\x1a\x0efunction.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc9\x02\n" +
	"\bInstance\x12.\n" +
	"\bfunction\x18\x01 \x01(\v2\x12.function.FunctionR\bfunction\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04addr\x18\x03 \x01(\tR\x04addr\x12\x1f\n" +
	"\vreplica_set\x18\x04 \x01(\tR\n" +
	"replicaSet\x12;\n" +
	"\vassigned_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"assignedAt\x125\n" +
	"\bready_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\areadyAt\x12&\n" +
	"\x0fcpu_usage_milli\x18\a \x01(\rR\rcpuUsageMilli\x12(\n" +
	"\x10memory_usage_mib\x18\b \x01(\rR\x0ememoryUsageMibB1Z/github.com/gadget-inc/skipper/internal/functionb\x06proto3"

var file_instance_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_instance_proto_goTypes = []any{
	(*Instance)(nil),              // 0: function.Instance
	(*Function)(nil),              // 1: function.Function
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_instance_proto_depIdxs = []int32{
	1, // 0: function.Instance.function:type_name -> function.Function
	2, // 1: function.Instance.assigned_at:type_name -> google.protobuf.Timestamp
	2, // 2: function.Instance.ready_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_instance_proto_init() }
func file_instance_proto_init() {
	if File_instance_proto != nil {
		return
	}
	file_function_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_instance_proto_rawDesc), len(file_instance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_instance_proto_goTypes,
		DependencyIndexes: file_instance_proto_depIdxs,
		MessageInfos:      file_instance_proto_msgTypes,
	}.Build()
	File_instance_proto = out.File
	file_instance_proto_goTypes = nil
	file_instance_proto_depIdxs = nil
}
