// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: scale.proto

package function

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Scale struct {
	state                             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_MinInstances           uint32                 `protobuf:"varint,1,opt,name=min_instances,json=minInstances,proto3"`
	xxx_hidden_MaxInstances           uint32                 `protobuf:"varint,2,opt,name=max_instances,json=maxInstances,proto3"`
	xxx_hidden_TargetCpuUsageMilli    uint32                 `protobuf:"varint,3,opt,name=target_cpu_usage_milli,json=targetCpuUsageMilli,proto3"`
	xxx_hidden_TargetMemoryUsageMib   uint32                 `protobuf:"varint,4,opt,name=target_memory_usage_mib,json=targetMemoryUsageMib,proto3"`
	xxx_hidden_TargetInFlightRequests uint32                 `protobuf:"varint,5,opt,name=target_in_flight_requests,json=targetInFlightRequests,proto3"`
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *Scale) Reset() {
	*x = Scale{}
	mi := &file_scale_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scale) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scale) ProtoMessage() {}

func (x *Scale) ProtoReflect() protoreflect.Message {
	mi := &file_scale_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Scale) GetMinInstances() uint32 {
	if x != nil {
		return x.xxx_hidden_MinInstances
	}
	return 0
}

func (x *Scale) GetMaxInstances() uint32 {
	if x != nil {
		return x.xxx_hidden_MaxInstances
	}
	return 0
}

func (x *Scale) GetTargetCpuUsageMilli() uint32 {
	if x != nil {
		return x.xxx_hidden_TargetCpuUsageMilli
	}
	return 0
}

func (x *Scale) GetTargetMemoryUsageMib() uint32 {
	if x != nil {
		return x.xxx_hidden_TargetMemoryUsageMib
	}
	return 0
}

func (x *Scale) GetTargetInFlightRequests() uint32 {
	if x != nil {
		return x.xxx_hidden_TargetInFlightRequests
	}
	return 0
}

func (x *Scale) SetMinInstances(v uint32) {
	x.xxx_hidden_MinInstances = v
}

func (x *Scale) SetMaxInstances(v uint32) {
	x.xxx_hidden_MaxInstances = v
}

func (x *Scale) SetTargetCpuUsageMilli(v uint32) {
	x.xxx_hidden_TargetCpuUsageMilli = v
}

func (x *Scale) SetTargetMemoryUsageMib(v uint32) {
	x.xxx_hidden_TargetMemoryUsageMib = v
}

func (x *Scale) SetTargetInFlightRequests(v uint32) {
	x.xxx_hidden_TargetInFlightRequests = v
}

type Scale_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	MinInstances           uint32
	MaxInstances           uint32
	TargetCpuUsageMilli    uint32
	TargetMemoryUsageMib   uint32
	TargetInFlightRequests uint32
}

func (b0 Scale_builder) Build() *Scale {
	m0 := &Scale{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_MinInstances = b.MinInstances
	x.xxx_hidden_MaxInstances = b.MaxInstances
	x.xxx_hidden_TargetCpuUsageMilli = b.TargetCpuUsageMilli
	x.xxx_hidden_TargetMemoryUsageMib = b.TargetMemoryUsageMib
	x.xxx_hidden_TargetInFlightRequests = b.TargetInFlightRequests
	return m0
}

var File_scale_proto protoreflect.FileDescriptor

const file_scale_proto_rawDesc = "" +
	"\n" +
	"\vscale.proto\x12\bfunction\"\xf8\x01\n" +
	"\x05Scale\x12#\n" +
	"\rmin_instances\x18\x01 \x01(\rR\fminInstances\x12#\n" +
	"\rmax_instances\x18\x02 \x01(\rR\fmaxInstances\x123\n" +
	"\x16target_cpu_usage_milli\x18\x03 \x01(\rR\x13targetCpuUsageMilli\x125\n" +
	"\x17target_memory_usage_mib\x18\x04 \x01(\rR\x14targetMemoryUsageMib\x129\n" +
	"\x19target_in_flight_requests\x18\x05 \x01(\rR\x16targetInFlightRequestsB1Z/github.com/gadget-inc/skipper/internal/functionb\x06proto3"

var file_scale_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_scale_proto_goTypes = []any{
	(*Scale)(nil), // 0: function.Scale
}
var file_scale_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_scale_proto_init() }
func file_scale_proto_init() {
	if File_scale_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scale_proto_rawDesc), len(file_scale_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_scale_proto_goTypes,
		DependencyIndexes: file_scale_proto_depIdxs,
		MessageInfos:      file_scale_proto_msgTypes,
	}.Build()
	File_scale_proto = out.File
	file_scale_proto_goTypes = nil
	file_scale_proto_depIdxs = nil
}
