name: cd

on:
  push:
    branches:
      - main

permissions:
  contents: "read"
  id-token: "write"

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml
  cd:
    needs: ci
    runs-on: depot-ubuntu-latest-8
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Depot
        uses: depot/setup-action@v1
        with:
          oidc: true

      - name: Configure Depot
        run: |
          depot configure-docker --project=${{ secrets.DEPOT_PROJECT_ID }}

      - name: Authenticate gcloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.GCLOUD_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_EMAIL }}

      - name: Login to Google Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: us-central1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build and push to Google Artifact Registry
        run: |
          task build -- \
            --repo=us-central1-docker.pkg.dev/gadget-core-production/core-production/skipper \
            --platform=linux/amd64,linux/arm64 \
            --cache-from-to=registry \
            --push \
            --no-kind
