name: cd

on:
  push:
    branches:
      - main

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml
  cd:
    needs: ci
    runs-on: ubuntu-latest-l
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment
        uses: ./.github/actions/setup-environment

      - name: Set up Docker
        uses: ./.github/actions/setup-docker

      - name: Authenticate gcloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.GCLOUD_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_EMAIL }}

      - name: Login to Google Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: us-central1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build and push to Google Artifact Registry
        run: |
          task build -- \
            --registry=us-central1-docker.pkg.dev/gadget-core-production/core-production \
            --platform=linux/amd64,linux/arm64 \
            --cache-from-to=registry \
            --push \
            --no-kind
