name: ci

on:
  workflow_call:
  pull_request:

jobs:
  go-lint:
    runs-on: depot-ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    env:
      DEPOT_PROJECT_ID: ${{ secrets.DEPOT_PROJECT_ID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Setup Depot
        uses: depot/setup-action@v1
        with:
          oidc: true

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          install-mode: "none"

  go-test:
    runs-on: depot-ubuntu-latest-8
    permissions:
      contents: "read"
      id-token: "write"
    env:
      DEPOT_PROJECT_ID: ${{ secrets.DEPOT_PROJECT_ID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup Depot
        uses: depot/setup-action@v1
        with:
          oidc: true

      - name: Configure Depot
        run: |
          depot configure-docker --project ${{ secrets.DEPOT_PROJECT_ID }}

      - name: Create kind cluster
        run: |
          cat << EOF > kind-config.yaml
          kind: Cluster
          apiVersion: kind.x-k8s.io/v1alpha4
          nodes:
          - role: control-plane
            extraPortMappings:
            - containerPort: 31020
              hostPort: 31020
            - containerPort: 31021
              hostPort: 31021
          EOF
          kind create cluster --config=kind-config.yaml

      - name: Deploy
        env:
          KUBECTL_CONTEXT: kind-kind
        run: task deploy-all

      - name: Watch and persist logs
        run: |
          mkdir -p tmp/logs/
          nohup stern . --namespace=skipper-test,skipper-test-fixtures --template='{{ printf "%s/%s: %s\n" .Namespace .PodName .Message }}' | tee tmp/logs/stern.log &

      - name: Run tests
        env:
          LOG_LEVEL: debug
        run: |
          mkdir -p tmp/logs/
          task test | tee tmp/logs/test.log

      - if: always()
        name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: tmp/logs/

  deno-lint:
    runs-on: depot-ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    env:
      DEPOT_PROJECT_ID: ${{ secrets.DEPOT_PROJECT_ID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Run lint
        run: deno lint
