name: ci

on:
  push:
  workflow_call:
  pull_request:

env:
  GOPATH: /home/runner/go
  DENO_DIR: /home/runner/.deno

jobs:
  go-lint:
    runs-on: ubuntu-latest
    env:
      GOLANGCI_LINT_CACHE: /home/runner/.cache/golangci-lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          install-mode: "none"
          args: "--timeout 10m"

  go-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Deploy test environment
        env:
          KUBECTL_CONTEXT: kind-kind
        run: |
          kind create cluster
          task deploy-all --concurrency=1

      - name: Run tests
        run: go test -v ./...

  deno-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Run lint
        run: deno lint
