name: release

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        platform: [amd64, arm64]
        include:
          - platform: amd64
            runner: blacksmith-8vcpu-ubuntu-2404
          - platform: arm64
            runner: blacksmith-8vcpu-ubuntu-2404-arm
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment
        uses: ./.github/actions/setup-environment
        with:
          cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Set up Docker
        uses: ./.github/actions/setup-docker

      - name: Authenticate gcloud
        id: auth
        uses: google-github-actions/auth@v3
        with:
          token_format: access_token
          workload_identity_provider: ${{ vars.GCLOUD_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.GCLOUD_SERVICE_ACCOUNT_EMAIL }}

      - name: Login to Google Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: us-central1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build and push ${{ matrix.platform }} image to Google Artifact Registry
        run: |
          build \
            --only=skipper \
            --registry=us-central1-docker.pkg.dev/gadget-core-production/core-production \
            --push \
            --no-kind

  merge-manifests:
    needs: build
    runs-on: blacksmith-2vcpu-ubuntu-2404
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment
        uses: ./.github/actions/setup-environment
        with:
          cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Set up Docker
        uses: ./.github/actions/setup-docker

      - name: Authenticate gcloud
        id: auth
        uses: google-github-actions/auth@v3
        with:
          token_format: access_token
          workload_identity_provider: ${{ vars.GCLOUD_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.GCLOUD_SERVICE_ACCOUNT_EMAIL }}

      - name: Login to Google Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: us-central1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Merge images into a multi-architecture manifest and push to Google Artifact Registry
        run: |
          sha=$(git rev-parse --short HEAD)

          docker manifest create "us-central1-docker.pkg.dev/gadget-core-production/core-production/skipper:sha-${sha}" \
              "us-central1-docker.pkg.dev/gadget-core-production/core-production/skipper:sha-${sha}-amd64" \
              "us-central1-docker.pkg.dev/gadget-core-production/core-production/skipper:sha-${sha}-arm64"

          docker manifest push "us-central1-docker.pkg.dev/gadget-core-production/core-production/skipper:sha-${sha}"
